#wx
APP_ID = "123"
APP_SECRET = "321"
ENCODING_AES_KEY = 'Your Encoding AES Key'
HOST = '127.0.0.1'
PORT = 5050
SESSION_STORAGE = None
SERVER = "auto"


#app
VER = 'v0.0.1'
PROJECT = 'wx'
DEBUG = True
DEBUG_TB_INTERCEPT_REDIRECTS = False